# This Gemfile comes from hydra-head/test_support/etc/Gemfile
# It's copied into the atrium test app by the rake atrium:setup_test_app task

source 'http://rubygems.org'

gem 'rails', '~> 3.1'
gem 'blacklight', '~> 3.3'
gem 'atrium', :path => '../../'

gem 'cancan'
gem 'devise'

group :assets do
  gem 'sass-rails'
  gem 'compass-rails', '~> 1.0.0'
  gem 'compass-susy-plugin', '~> 0.9.0'
  gem 'jquery-rails', '>= 1.0.12'
end

# For testing
group :development, :test do
  gem 'bcrypt-ruby'
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'factory_girl',  '~> 1.1'
  gem 'mocha'
  gem 'rspec'
  gem 'rspec-rails', '>=2.5.0'
  gem 'ruby-debug'
  gem 'sqlite3'
end
